### ISSUE TITLE
Does PYNQ OS v2.5 include PyTorch? 

### ISSUE THREAD

**Issue by kamotsuru** [manoharvhr/PYNQ-Torch#2]
Although the 3rd paragraph of section II in your IEEE publication describes that PYNQ OS v2.5 includes PyTorch v1.2.0, I can't import torch to the python in the image.
Am I something wrong?

xilinx@pynq:~$ more REVISION 
Release 2019_10_03 3f63450
xilinx@pynq:~$ python3
Python 3.6.5 (default, Apr  1 2018, 05:46:30) 
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'torch'
>>>

**Comment by manoharvhr** [comment]
Hi,

You have to actually follow the steps mentioned in this repository or download the image file which has it done already.
________________________________

**Comment by manoharvhr** [comment]
Actually, I looked back at the article and it was meant to say v2.4, which is available in the [Releases tab](https://github.com/manoharvhr/PYNQ-Torch/releases/tag/v1.0) of this repository. However, if you wish to use the latest PYNQ version (which may have new features), I am sure that the steps to install PyTorch available [here](https://github.com/manoharvhr/PYNQ-Torch/tree/master/PyTorch_Installation) will be compatible.

**Comment by kayalvizhimuthu** [comment]
Hi, i download the tar file and follow the below steps..resultant i got tar file i write into sd card using etcher..but board not boot
sudo su
cat PYNQ_1.tar.gz.parta* > PYNQ_1.tar.gz

**Comment by manoharvhr** [comment]
Which board are you trying to use?

**Comment by kayalvizhimuthu** [comment]
I am using PYNQ Z1 board.

**Comment by kayalvizhimuthu** [comment]
First i downloaded pynqv2.4 image from your github page, and write
sdcard then follow steps to install pytorch .....python3 setup.py build- in
this command executed at 75% after i got error...
then i tried compressed preinstalled image file...i downloaded all files
and follow your steps

sudo su
cat PYNQ_1.tar.gz.parta* > PYNQ_1.tar.gz

then i got a tar file...i canot extract this file.. i wrote tar file
in sd card..but pynq board not boot...plz can you share pre installed
pytorch on pynq image...

**Comment by manoharvhr** [comment]
Did you manage to get it working?
The pre installed image is what you are using.
