### ISSUE TITLE
Problem with installing torchvision

### ISSUE THREAD

**Issue by sanjayamv** [manoharvhr/PYNQ-Torch#3]
Hi Manohar,
This is a great project and I have found it to be very helpful. Currently I am using Pynq which I have built for ZCU-102 and was able to successfully install pytorch as per your instructions. But I want to install torchvision package on the same and I am unable to do it. I tried directly installing through pip, tried to install conda, tried building from source , but nothing worked. Is it possible to install Torchvision on this ??

**Comment by manoharvhr** [comment]
Hi,

Usually pip and conda do not have packages designed for these boards. I recommend building it from source like I did for PyTorch. The source is available [here](https://github.com/pytorch/vision). Give that a go and let me know if you were successful.

**Comment by manoharvhr** [comment]
Hey, were you able to install it?

**Comment by sanjayamv** [comment]
Hey ... Sorry for the very late reply ...
No I was not able to install it. I tried installing it from source itself. Since the pytorch version installed was 1.2 , I tried installing the compatable 0.4 version of torchvision. I got the git repo of torchvision and run this cmd : " python3 setup.py install version=0.4 "

I got the following error :
  File "setup.py", line 14, in <module>
    from torch.utils.hipify import hipify_python
ModuleNotFoundError: No module named 'torch.utils.hipify' 

I am not sure if this is due to some version incompatibility !!

**Comment by sanjayamv** [comment]
Hey ... Sorry for the very late reply
No I was not able to install it. Since I had the 1.2 version of pytorch installed , I got the torchvision git repo of v.0.4 and tried installing it on my device .
I am using python3 to install it : python3 setup.py install

>>> import torch
>>> torch.__version__
'1.2.0a0+8554416'

I am getting the following error : 
......
aarch64-linux-gnu-gcc: error: /home/xilinx/vision-0.4.0/torchvision/csrc/models/mobilenet.cpp: No such file or directory
aarch64-linux-gnu-gcc: fatal error: no input files
compilation terminated.
error: command 'aarch64-linux-gnu-gcc' failed with exit status 1

I am not sure what input files its expecting .

**Comment by sanjayamv** [comment]
I was able to install torchvision v0.4.0 using instructions the following the link ( ARM processor on both jetson nano and ZCU-102) :
https://forums.developer.nvidia.com/t/pytorch-for-jetson-version-1-7-0-now-available/72048

Although pytorch installation failed using those pytorch wheels ( I am not sure why, but could be requiring jetpack ) , I was able to get torchvision running on the preinstalled pytorch 1.2 .
