### ISSUE TITLE
Python version require

### ISSUE THREAD

**Issue by Force1ess** [manoharvhr/PYNQ-Torch#5]
Recently, I tried your tutorial to install pytorch .But it went wrong and notice me that python version should be more than 3.6 . I tried many ways to install python. Source code install is too slow, it even cannot finish install in two days. How you solve this problem？ THANK YOU FOR YOUR PATIENCE

**Comment by manoharvhr** [comment]
Which python version do you want to install it for?
________________________________
From: Forceless ***@***.***>
Sent: Tuesday, March 30, 2021 3:14:47 AM
To: manoharvhr/PYNQ-Torch ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [manoharvhr/PYNQ-Torch] Python version require (#5)


Recently, I tried your tutorial to install pytorch .But it went wrong and notice me that python version should be more than 3.6 . I tried many ways to install python. Source code install is too slow, it even cannot finish install in two days. How you solve this problem？ THANK YOU FOR YOUR PATIENCE

**Comment by Force1ess** [comment]
<h1>Follow your tutorial and tried again.</h1>
It worked and don't warning me again, but it's too long to build this.<br>
It's my curiosity to ask you how many times you spend on building this.<br>
And if you can offer us a .wheel package, it's better and I'm more appreciate you.<br>
Or this package already exists but I haven't found it, please guide me.<br>
<h2>But some errors happend, wish you could help me fix it.</h2>
I leave my Error  log files and screenshots in the downside link<br>
<h2>Anyway, thank you for your tutorials and your patience.<br>
Salute🤟</h2>
<a href="https://drive.google.com/drive/folders/1BBlIY2anuGanrIA9j6UcGloPAxBVz4H9?usp=sharing">Click me</a>

**Comment by manoharvhr** [comment]
You can download the image file I have in releases. It is expected to take long. I cannot view the error log.

**Comment by Force1ess** [comment]
#Already solved
##thanks for your selfless contribution, now I've make it effective.
##It cannot be install because I believe in these retailers, can't believe they deliver me a z2 with v2.2 pynq version
#Anyway, thanks
