### ISSUE TITLE
How to enable networking on Zynq-7020?

### ISSUE THREAD

**Issue by YangHecctor** [manoharvhr/PYNQ-Torch#6]
Your work is fascinating and can greatly accelerate development speed, but how do we connect the development board to the internet?

**Comment by manoharvhr** [comment]
The board has an ethernet port which you should be able to use.

**Comment by YangHecctor** [comment]
I connected the board to the router, and then connected the router to the computer. This way, the board can access the internet, and the computer can also open a terminal.
